# Microprofile server properties
server:
  port: 8080
  host: 0.0.0.0

# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics:
  rest-request:
    enabled: false

oracle:
  ucp:
    jdbc:
      PoolDataSource:
        atp:
          URL:
          connectionFactoryClassName: oracle.jdbc.replay.OracleDataSourceImpl
          user:
          password:
          connectionPoolName: JDBC_UCP_POOL
          initialPoolSize: 1
          minPoolSize: 1
          maxPoolSize: 1
          timeoutCheckInterval: 10
          inactiveConnectionTimeout: 10
          queryTimeout: 600
          fastConnectionFailoverEnabled: false
