@localhost = http://localhost
@product = 8080
@customer = 8081
@order = 8082
@payment = 8083

#####
# Products
#####
### Health Check
GET {{localhost}}:{{product}}/health HTTP/1.1

###
GET {{localhost}}:{{product}}/metrics HTTP/1.1

### Get all products
GET {{localhost}}:{{product}}/products HTTP/1.1

### Get product by id - success
GET {{localhost}}:{{product}}/products/1 HTTP/1.1

### Get product by id - failed(404)
GET {{localhost}}:{{product}}/products/999 HTTP/1.1

### Create Product
POST {{localhost}}:{{product}}/products HTTP/1.1
Content-Type: application/json

{
    "id": 999,
    "name": "Product Z",
    "description": "Description for Product Z.",
    "price": 9999,
    "quantity": 99
}

### Update Product
PUT {{localhost}}:{{product}}/products HTTP/1.1
Content-Type: application/json

{
    "id": 999,
    "name": "Product ZZZ",
    "description": "Description for Product ZZZ.",
    "price": 9999,
    "quantity": 999999
}

### Delete Product
DELETE {{localhost}}:{{product}}/products/999 HTTP/1.1

#####
# Customers
#####
GET {{localhost}}:{{customer}}/health HTTP/1.1

### Get all customers
GET {{localhost}}:{{customer}}/customers HTTP/1.1

### Get customer by id - success
GET {{localhost}}:{{customer}}/customers/1 HTTP/1.1

### Get customer by id - failed
GET {{localhost}}:{{customer}}/customers/999 HTTP/1.1

### Create customer
POST {{localhost}}:{{customer}}/customers HTTP/1.1
Content-Type: application/json

{
    "id": 999,
    "firstName": "First 999",
    "lastName": "Last 999",
    "email": "email999@example.com",
    "phoneNumber": "123-456-7891"
}

### Update customer
PUT {{localhost}}:{{customer}}/customers HTTP/1.1
Content-Type: application/json

{
    "id": 999,
    "firstName": "First 999+",
    "lastName": "Last 999+",
    "email": "email999+@example.com",
    "phoneNumber": "123-456-7891"
}

### Delete customer
DELETE {{localhost}}:{{customer}}/customers/999 HTTP/1.1

#####
# Order
#####
GET {{localhost}}:{{order}}/health HTTP/1.1

###
GET {{localhost}}:{{order}}/orders HTTP/1.1

### status - shipped
GET {{localhost}}:{{order}}/orders/1 HTTP/1.1

### status - delivered
GET {{localhost}}:{{order}}/orders/2 HTTP/1.1

### status - processing
GET {{localhost}}:{{order}}/orders/3 HTTP/1.1

### not found
GET {{localhost}}:{{order}}/orders/999 HTTP/1.1

###
POST {{localhost}}:{{order}}/orders HTTP/1.1
Content-Type: application/json

{
    "id": 999,
    "customerId": "1",
    "totalPrice": "9999"
}

###
PUT {{localhost}}:{{order}}/orders HTTP/1.1
Content-Type: application/json

{
    "id": 999,
    "customerId": "1",
    "totalPrice": "9999999"
}

###
DELETE {{localhost}}:{{order}}/orders/999 HTTP/1.1

#####
# Payment
#####
GET {{localhost}}:{{payment}}/health HTTP/1.1

###
GET {{localhost}}:{{payment}}/payments HTTP/1.1

###
GET {{localhost}}:{{payment}}/payments/1 HTTP/1.1

###
GET {{localhost}}:{{payment}}/payments/999 HTTP/1.1

###
POST {{localhost}}:{{payment}}/payments HTTP/1.1
Content-Type: application/json

{
    "id": 999,
    "orderId": 1,
    "paymentMethod": "PAYPAL",
    "amount": 999
}

###
PUT {{localhost}}:{{payment}}/payments HTTP/1.1
Content-Type: application/json

{
    "id": 999,
    "orderId": 1,
    "paymentMethod": "PAYPAL",
    "amount": 999999
}

###
DELETE {{localhost}}:{{payment}}/payments/999 HTTP/1.1