----------------------
-- products
----------------------
DROP TABLE products;

CREATE TABLE products (
    id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(2000),
    price  NUMBER(6,0) NOT NULL,
    image_url VARCHAR2(255)
);

INSERT INTO products (name, description, price, image_url) VALUES ('Product A', 'Description for Product A.', 1000, 'https://example.com/image_a.jpg');
INSERT INTO products (name, description, price, image_url) VALUES ('Product B', 'Description for Product B.', 2000, 'https://example.com/image_b.jpg');
INSERT INTO products (name, description, price, image_url) VALUES ('Product C', 'Description for Product C.', 3000, 'https://example.com/image_c.jpg');
INSERT INTO products (name, description, price, image_url) VALUES ('Product D', 'Description for Product D.', 4000, 'https://example.com/image_d.jpg');
INSERT INTO products (name, description, price, image_url) VALUES ('Product E', 'Description for Product E.', 5000, 'https://example.com/image_e.jpg');

commit;